### ISSUE TITLE
QTaste is not working well if installed in a directory containing spaces

### ISSUE THREAD

**Issue by qspin** [qspin/qtaste#7]
QTaste doesn't like path containing spaces. Ex: On windows platform, don't install it in Program Files.

It seems to come from limitation in some shell script not so trivial to fix.

**Comment by remybaranx** [comment]
I'm working on this ticket and, for the moment, I've found some issues : 

1) There is a mistake in linux bash scripts. When a path contains spaces, it must be surrounded by quotes. So, `dirname $0` must be replaced by `dirname "$0"`. But I think a better solution is to move to the QTaste directory at the beginning of the script in order to avoid handling path with spaces.

2) In TestEngine.java / startOrStopSUT() : if the "-Dpython.path=" option contains a path with spaces, jython does not find the jython jar file. I'm trying to find a solution.

**Comment by remybaranx** [comment]
For the second point, the problem is due to Runtime.getRuntime().exec(...) in Exec.java. This exec function will split the 'cmd' argument into a map of strings, using a StringTokeniser (see : http://stackoverflow.com/questions/4916918/java-execute-a-command-with-a-space-in-the-pathname).

A solution is to call directly the exec function which takes a map of strings as command argument. Another solution is to use the ProcessBuilder class.

**Comment by remybaranx** [comment]
This bug has been fixed on Linux but still exists on Windows ...
I have asked a question on stackoverflow : http://stackoverflow.com/questions/29678058/classpath-with-spaces-for-a-java-process-launch-with-runtime-getruntime-exec

**Comment by remybaranx** [comment]
Interesting link : https://blogs.oracle.com/thejavatutorials/entry/changes_to_runtime_exec_problems

**Comment by remybaranx** [comment]
This issue has been fixed in the branch control_script_2.7 (JYTHONPATH support is required and is available from jython 2.5).
Tested on Linux (Ubuntu 14.04) and Windows 8.1

**Comment by lvboque** [comment]
it is indeed working on linux but not fixed on windows platform
